/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pkkg
 */
public class Add_Item extends javax.swing.JFrame {

    /**
     * Creates new form Add_Item
     */
    public Add_Item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_type = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_buyp = new javax.swing.JTextField();
        txt_sellp = new javax.swing.JTextField();
        txt_code = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_wuniq = new javax.swing.JTextField();
        txt_buniq = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        cmb_type = new javax.swing.JComboBox<>();
        cmb_psize = new javax.swing.JComboBox<>();
        cmb_category = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Kelso Lanka(Pvt)Ltd.");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/navigation.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sales Management");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webp.net-resizeimage (3).png"))); // NOI18N

        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_name.setText("Username");

        lbl_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_type.setText("Type");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel2))
                .addContainerGap(1017, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_type)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_type)
                            .addComponent(lbl_name)))))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1381, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backnew.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel5.setText(" Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel6.setText("Item code");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jLabel7.setText("World Unique");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        jLabel8.setText("Branch Unique");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, -1, -1));

        jLabel9.setText("Engine Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, -1, -1));

        jLabel10.setText("Pack Size");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 421, -1, -1));

        jLabel13.setText("Buying Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        jLabel16.setText("Category");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, -1, -1));

        jLabel17.setText("Selling Price");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        txt_id.setEditable(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 110, -1));
        getContentPane().add(txt_buyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 110, -1));
        getContentPane().add(txt_sellp, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 110, -1));
        getContentPane().add(txt_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 110, -1));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 110, -1));
        getContentPane().add(txt_wuniq, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 110, -1));
        getContentPane().add(txt_buniq, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 110, -1));
        getContentPane().add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 110, -1));

        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Petrol", "Diesel", "Electric", "Hybrid" }));
        getContentPane().add(cmb_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 110, -1));

        cmb_psize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO PACK SIZE", "400ml", "1L", "2L", "4L" }));
        getContentPane().add(cmb_psize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 110, -1));

        cmb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LUBRICANT", "AIR FILTER", "FUEL FILTER", "OIL FILTER", "CHEMICALS" }));
        getContentPane().add(cmb_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, 110, -1));

        jLabel18.setText("Quantity");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        jButton1.setText("Delete Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 320, 190, 60));

        jButton2.setText("Clear");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 710, 110, 30));

        jButton3.setText("Add Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 710, 110, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        PreparedStatement pst;
      Connection con;
        Statement st;
  
    void clear()
    {
        txt_name.setText("");
        txt_code.setText("");
        txt_buniq.setText("");
        txt_buyp.setText("");
        txt_quantity.setText("");
        txt_sellp.setText("");
        txt_wuniq.setText("");
        
    }
    void getid() throws Exception
    {
        try
        {
          con= DB.createConnection();
          String id="select MAX(ID) as max_id from products ";
       PreparedStatement   pst=con.prepareStatement(id);
          ResultSet rst=pst.executeQuery(id);
         while( rst.next())
                  {
                       int newid=0;
          newid=rst.getInt("max_id");
        int  neewesstid=newid+1;
          txt_id.setText(neewesstid+"");
         
                  }
          con.close();
          
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex);
            con.close();
        }        
        
    }
    void Add_Item()
{
    int buy,sell,profit;
    buy=Integer.parseInt(txt_buyp.getText());
    sell=Integer.parseInt(txt_sellp.getText());
    profit=sell-buy;
    
    try 
            {
                Connection con = DB.createConnection();
                String sql = "INSERT INTO products (ID,Name,Item_code,World_unique,Branch_unique,Engine_type,Pack_size,Quantity,Buying_price,Selling_price,Profit,Category) VALUES ('" + txt_id.getText() + "', '" + txt_name.getText() + "' , '" + txt_code.getText() + "','" + txt_wuniq.getText() + "','" + txt_buniq.getText() + "','" + cmb_type.getSelectedItem()+ "','"+cmb_psize.getSelectedItem()+ "','" + txt_quantity.getText() + "','" + txt_buyp.getText() + "','" + txt_sellp.getText() + "','"+profit+"','" + cmb_category.getSelectedItem()+ "')";
                PreparedStatement stmt = con.prepareStatement(sql);
                int i = stmt.executeUpdate();

                if (i == 1) 
                {
                    JOptionPane.showMessageDialog(this, "Successfully Added a New Item.", "Done", JOptionPane.PLAIN_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Cannot Add Item. Try Again","Error  ",JOptionPane.ERROR_MESSAGE);
                }

            } 
            
            catch(SQLException e)
            {JOptionPane.showMessageDialog(null,e);
               // JOptionPane.showMessageDialog(this,"Database Error. Please Try Again","Database Error",JOptionPane.ERROR_MESSAGE);
            }
            catch (Exception e) 
            {
                JOptionPane.showMessageDialog(this,"Please Try Again","Error  " + e,JOptionPane.ERROR_MESSAGE);
            }
            
}
void vali()
{
   try
   {
        if(txt_name.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this,"Name Cannot Be Blank","Error  ",JOptionPane.ERROR_MESSAGE);
    }
    
     else if(txt_buyp.getText().equals(""))
    {
      JOptionPane.showMessageDialog(this,"Buying Price Cannot Be Blank","Error  ",JOptionPane.ERROR_MESSAGE);  
    }
    
       else if(txt_quantity.getText().equals(""))
    {
      JOptionPane.showMessageDialog(this,"Quantity Cannot Be Blank","Error  ",JOptionPane.ERROR_MESSAGE); 
    }
        else if(txt_sellp.getText().equals(""))
    {
      JOptionPane.showMessageDialog(this,"Selling Price Cannot Be Blank","Error  ",JOptionPane.ERROR_MESSAGE);
    }
        
    else
    {Integer.parseInt(txt_buyp.getText());
    Integer.parseInt(txt_sellp.getText());
    Integer.parseInt(txt_quantity.getText());
       Add_Item(); 
    }
   }
   catch(NumberFormatException ex)
           {
               JOptionPane.showMessageDialog(this,"Selling Price,Buuying Price,Quantity Cannot Be Letters","Error  ",JOptionPane.ERROR_MESSAGE); 
           }
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            getid();
        } catch (Exception ex) {
            Logger.getLogger(Add_Item.class.getName()).log(Level.SEVERE, null, ex);
        }
        get_user_details();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        
        new Admin_Menu(name, type).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
vali();
        try {
            getid();// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Add_Item.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Delete_Item(name, type).setVisible(true);
this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
public Add_Item(String name,String type)
{
    initComponents();
       lbl_name.setText(name);
       lbl_type.setText(type);
       lbl_name.setVisible(true);
       lbl_type.setVisible(true);
}
 String name,type;
    void get_user_details()
    {
        name=lbl_name.getText();
        type=lbl_type.getText();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_category;
    private javax.swing.JComboBox<String> cmb_psize;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JTextField txt_buniq;
    private javax.swing.JTextField txt_buyp;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_sellp;
    private javax.swing.JTextField txt_wuniq;
    // End of variables declaration//GEN-END:variables
}
